// src/components/molecules/EduListItem.vue
<script setup>
    import { RouterLink } from 'vue-router';
    import LargeBoldText from '../atoms/LargeBoldText.vue';
    import DateRange from '../atoms/DateRange.vue';
    import DropdownButton from './DropdownButton.vue';

    const props = defineProps({
        schoolName: String,
        startDate: String,
        endDate: String,
        schoolUrl: String,
        detailUrl: String
    })

    const formattedUrl = `https://${props.schoolUrl}`
</script>

<template>
    <div>
        <div class="flex justify-between items-center">
            <LargeBoldText :text="schoolName" />
            <DropdownButton title="View menu">
                <a :href="formattedUrl" title="School's website" class="block py-2 px-3 hover:bg-primary-300">School's website</a>
                <RouterLink :to="detailUrl" title="View details" class="block py-2 px-3 hover:bg-primary-300">More details</RouterLink>
            </DropdownButton>
        </div>
        <DateRange :start-date="startDate" :end-date="endDate" />
        <slot />
    </div>
</template>

// src/lib/components/organisms/edu_list_item.svelte
<script>
	import DateRangeDisplay from '../atoms/date_range_display.svelte';
	import LargeBoldText from '../atoms/large_bold_text.svelte';
	import DropDownButton from './drop_down_button.svelte';

	/**
	 * @type {String}
	 */
	export let name;

	/**
	 * @type {String}
	 */
	export let startDate;

	/**
	 * @type {String}
	 */
	export let endDate;

	/**
	 * @type {String}
	 */
	export let id;

	/**
	 * @type {String}
	 */
	export let url;
</script>

<div {id}>
	<div class="flex justify-between items-center">
		<LargeBoldText text={name} />
		<DropDownButton title="View menu" buttonId="{id}_dropdown">
			<a href="https://www.{url}" title="School site" class="block py-2 px-3 hover:bg-primary-300"
				>School site</a
			>
			<a href="/{id}" title="More details" class="block py-2 px-3 hover:bg-primary-300">More details</a>
		</DropDownButton>
	</div>
	<div class="my-3">
	   <DateRangeDisplay {startDate} {endDate} />
	</div>
	<slot />
</div>
