// src/components/organisms/WorkExpItem.vue
<script setup>
import LargeBoldText from '../atoms/LargeBoldText.vue';
import DateRange from '../molecules/DateRange.vue';

defineProps({
    name: String,
    employer: String,
    startDate: String,
    endDate: String,
    description: String
})
</script>

<template>
    <LargeBoldText :text="name" />
    <p class="py-3">{{ employer }}</p>
    <DateRange :start-date="startDate" :end-date="endDate" />
    <p v-if="description != null" class="pt-2">
        {{ description }}
    </p>
</template>

// src/lib/components/organisms/work_exp_item.svelte
<script>
  import DateRange from '../molecules/date_range.svelte'

  /**
   * @type {String}
   */
  export let name

  /**
   * @type {String}
   */
  export let employer

  /**
   * @type {String}
   */
  export let startDate

  /**
   * @type {String?}
   */
  export let endDate = null

  /**
   * @type {String?}
   */
  export let description = null

  export let classes = '';
</script>

<div class="{classes}">
    <p class="font-bold">{name}</p >
    <p class="pb-3 text-sm">{employer}</p>
    <DateRange {startDate} {endDate} />

    {#if description !== null}
      <p class="text-justify pt-3">{description}</p>
    {/if}
</div >
