// src/components/molecules/WorkExpListItem.vue
<script setup>
    import DateRange from '../atoms/DateRange.vue';
    import LargeBoldText from '../atoms/LargeBoldText.vue';

    const prop = defineProps({
        position: String,
        employer: String,
        startDate: String,
        endDate: {
            type: String,
            required: false
        },
        description: {
            type: String,
            required: false
        }
    })
</script>

<template>
    <LargeBoldText :text="position" />
    <p class="py-2">{{ employer }}</p>
    <DateRange :start-date="startDate" :end-date="endDate" />
    <p v-if="description != undefined" class="text-justify">{{ description }}</p>
</template>

// src/lib/components/organisms/work_exp_list_item.svelte
<script>
	import DateRangeDisplay from '../atoms/date_range_display.svelte';
	import LargeBoldText from '../atoms/large_bold_text.svelte';

	/**
	 * @type {String}
	 */
	export let name;

	/**
	 * @type {String}
	 */
	export let employer;

	/**
	 * @type {String}
	 */
	export let startDate;

	/**
	 * @type {String?}
	 */
	export let endDate = null;

	/**
	 * @type {String?}
	 */
	export let description = null;
</script>

<LargeBoldText text={name} />

<p class="py-3">{employer}</p>

<DateRangeDisplay {startDate} {endDate} />

{#if description !== null}
	<p class="text-justify pt-2">{description}</p>
{/if}
