// src/lib/components/molecules/date_range.svelte
<script>
  import Icon from '../atoms/icon.svelte'
  import Pill from '../atoms/pill.svelte'

  /**
   * @type {String}
   */
  export let startDate

  /**
   * @type {String?}
   */
  export let endDate
</script>

<p>
  <Icon icon="calendar" classes="me-1" />
  <span>
    {startDate}
    -
    {#if endDate != null}
      {endDate}
    {:else}
      <Pill text="Now" />
    {/if}
  </span>
</p>

// src/components/atoms/DateRange.vue
<script setup>
    import Icon from './Icon.vue';
    import Pill from './Pill.vue';

    const props = defineProps({
        startDate: String,
        endDate: {
            type: String,
            required: false
        }
    })
</script>

<template>
    <p class="py-2">
        <Icon icon="calendar" class="me-1" />
        <span v-if="endDate !== undefined">{{ startDate }} - {{ endDate }}</span>
        <span v-else>{{ startDate }} - <Pill text="now" /></span>
    </p>
</template>
