// src/lib/components/molecules/date_range.svelte
<script>
  import Icon from '../atoms/icon.svelte'
  import Pill from '../atoms/pill.svelte'

  /**
   * @type {String}
   */
  export let startDate

  /**
   * @type {String?}
   */
  export let endDate
</script>

<p>
  <Icon icon="calendar" classes="me-1" />
  <span>
    {startDate}
    -
    {#if endDate != null}
      {endDate}
    {:else}
      <Pill text="Now" />
    {/if}
  </span>
</p>

// src/components/molecules/DateRange.vue
<script setup>
import Icon from '../atoms/Icon.vue';
import Pill from '../atoms/Pill.vue';

defineProps({
    startDate: String,
    endDate: String
})
</script>

<template>
    <p class="py-2">
        <Icon icon="calendar" class="me-1" />
        {{ startDate }}
        -
        <span v-if="endDate != 'now'">{{ endDate }}</span>
        <Pill v-else text="now" />
    </p>
</template>
