// src/lib/components/molecules/DateRange.svelte
<script>
	import Icon from "../atoms/Icon.svelte";
	import Pill from "../atoms/Pill.svelte";

    /** @type {{startDate: string, endDate: string?}} */
    let { startDate, endDate } = $props();
</script>

<p>
    <Icon icon="calendar" classes="me-1" />
    <span>
        {startDate}
        -
        {#if endDate != null}
            {endDate}
        {:else}
            <Pill text="Now" />
        {/if}
    </span>
</p>

// src/components/molecules/DateRange.vue
<script setup>
import Icon from '../atoms/Icon.vue';
import Pill from '../atoms/Pill.vue';

defineProps({
    startDate: String,
    endDate: String
})
</script>

<template>
    <p class="py-2">
        <Icon icon="calendar" class="me-1" />
        {{ startDate }}
        -
        <span v-if="endDate != 'now'">{{ endDate }}</span>
        <Pill v-else text="now" />
    </p>
</template>
