// src/lib/components/organisms/oss_contribution_list_item.svelte
<script>
	import LargeBoldText from "../atoms/large_bold_text.svelte";
	import Link from "../atoms/link.svelte";

    /**
     * @type {String}
     */
    export let name;

    /**
     * @type {String}
     */
    export let description;

    /**
     * @type {String}
     */
    export let url;
</script>

<LargeBoldText text={name} />
<p class="py-2">{description}</p>
<p>Link: <Link url={url} title="Link to {name} project" content="Link" /></p>

// src/components/molecules/OssContributionListItem.vue
<script setup>
    import LargeBoldText from '../atoms/LargeBoldText.vue';
    import Link from '../atoms/Link.vue';

    const props = defineProps({
        name: String,
        description: String,
        url: String
    })
</script>

<template>
    <LargeBoldText :text="name" />
    <p class="py-2">
        {{ description }}
    </p>
    <p>Link: <Link :url="url" title="Link to the project site" content="Link" /></p>
</template>
