// src/lib/components/organisms/Project.svelte
<script>
	import Header from '../atoms/Header.svelte';

	/**
	 * @type {{ header: string, children: any, isFirst: boolean }}
	 */
	let { header, children, isFirst = false } = $props();

	const marginTop = isFirst ? 'mt-2' : 'mt-6';
</script>

<div class={marginTop}>
	<Header text={header} />
	<div class="px-5 pt-2 text-justify">
		{@render children?.()}
	</div>
</div>

// src/components/molecules/Project.vue
<script setup>
const props = defineProps({
  header: String,
  isFirst: {
    type: Boolean,
    default: false
  }
})
</script>

<template>
  <div :class="{ 'mt-2': isFirst, 'mt-5': !isFirst }">
    <div class="bg-primary-300 rounded py-2 px-3">
      <span class="font-bold">{{ header }}</span>
    </div>

    <div class="px-4 py-1 text-justify">
      <slot />
    </div>
  </div>
</template>
