// src/components/molecules/Project.vue
<script setup>
const props = defineProps({
  header: String,
  isFirst: {
    type: Boolean,
    default: false
  }
})
</script>

<template>
  <div :class="{ 'mt-2': isFirst, 'mt-5': !isFirst }">
    <div class="bg-primary-300 rounded py-2 px-3">
      <span class="font-bold">{{ header }}</span>
    </div>

    <div class="px-4 py-1 text-justify">
      <slot />
    </div>
  </div>
</template>

// src/lib/components/molecules/project.svelte
<script>
	import ProjectHeader from '../atoms/project_header.svelte';

	/**
	 * @type {String}
	 */
	export let header;

	export let isFirst = false;

	const marginTop = isFirst ? 'mt-2' : 'mt-5';
</script>

<div class={marginTop}>
	<ProjectHeader text={header} />
	<div class="px-3 pt-1 text-justify">
		<slot />
	</div>
</div>
