// src/lib/components/molecules/WorkExpItem.svelte
<script>
	import DateRange from "./DateRange.svelte";

    /** @type {{name: string, employer: string, startDate: string, endDate: string?, description: string?, classes: string}} */
    let { name, employer, startDate, endDate = null, description = null, classes = '' } = $props();
</script>

<div class="{classes}">
    <p class="font-bold">{name}</p >
    <p class="pb-3 text-sm">{employer}</p>
    <DateRange {startDate} {endDate} />

    {#if description !== null}
      <p class="text-justify pt-3">{description}</p>
    {/if}
</div >

// src/components/organisms/WorkExpItem.vue
<script setup>
import LargeBoldText from '../atoms/LargeBoldText.vue';
import DateRange from '../molecules/DateRange.vue';

defineProps({
    name: String,
    employer: String,
    startDate: String,
    endDate: String,
    description: String
})
</script>

<template>
    <LargeBoldText :text="name" />
    <p class="py-3">{{ employer }}</p>
    <DateRange :start-date="startDate" :end-date="endDate" />
    <p v-if="description != null" class="pt-2">
        {{ description }}
    </p>
</template>
