// src/lib/components/organisms/WorkExpItem.svelte
<script>
	import LargeBoldText from '../atoms/LargeBoldText.svelte';
	import DateRange from '../molecules/DateRange.svelte';

	/**
	 * @type {{ name: string, employer: string, startDate: string, description: string, endDate: string? }}
	 */
	let { name, employer, startDate, description, endDate = null } = $props();
</script>

<LargeBoldText text={name} />

<p class="py-3">{employer}</p>

<DateRange {startDate} {endDate} />

{#if description !== null}
	<p class="text-justify pt-2">{description}</p>
{/if}

// src/components/organisms/WorkExpItem.vue
<script setup>
import LargeBoldText from '../atoms/LargeBoldText.vue';
import DateRange from '../molecules/DateRange.vue';

defineProps({
    name: String,
    employer: String,
    startDate: String,
    endDate: String,
    description: String
})
</script>

<template>
    <LargeBoldText :text="name" />
    <p class="py-3">{{ employer }}</p>
    <DateRange :start-date="startDate" :end-date="endDate" />
    <p v-if="description != null" class="pt-2">
        {{ description }}
    </p>
</template>
